



обучение алгоритма LSTM 1...
обучение алгоритма ANN 1...
СКРИПТ ОБУЧЕНИЯ ANN 1 ЗАПУЩЕН...

> время загрузки библиотек : 1.674 сек.

(5570, 4)

> время чтения данных  :  1.744 сек.

компиляция НС...

> время компиляции НС  : 2.544 сек.

обучение НС...

Train on 4448 samples, validate on 1112 samples

Epoch 1/1

0s - loss: 0.0426 - acc: 0.0232 - val_loss: 0.1413 - val_acc: 0.2266

> время обучения НС  : 4.529 сек.

сохранение модели: D:\Anton\Desktop\MAIN\Экспертная система\Экспертная система\Алгоритмы прогнозирования\ANN 1\\weights.h5

> время сохранения НС  : 4.543 сек.

создание тестового прогноза

(1112, 1)

AVG = 0.503744353627

D:\Anton\Desktop\MAIN\Экспертная система\Экспертная система\Алгоритмы прогнозирования\ANN 1\predictions.txt

test_X.shape:  (1112, 10)

> время создания и записи тестового прогноза  : 4.677 сек.

______________END________________



Using Theano backend.

accuracy = 1
stdDev = 0,248586708715877
СКРИПТ ОБУЧЕНИЯ LSTM 1 ЗАПУЩЕН...

> время загрузки библиотек : 1.688 сек.

(5570, 4)

> время чтения данных  :  1.871 сек.

компиляция НС...

> время компиляции НС  : 2.650 сек.

обучение НС...

Train on 4448 samples, validate on 1112 samples

Epoch 1/1

0s - loss: 0.0617 - acc: 0.0207 - val_loss: 0.1564 - val_acc: 0.2149



Using Theano backend.
Traceback (most recent call last):
  File "D:\Anton\Desktop\MAIN\Экспертная система\Экспертная система\Алгоритмы прогнозирования\LSTM 1\train_script.py", line 102, in <module>
    model.save_weights(h("save_folder") + '\\' +  'weights.h5')
  File "C:\Anaconda3\lib\site-packages\keras\models.py", line 738, in save_weights
    f = h5py.File(filepath, 'w')
  File "C:\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 107, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (C:\Minonda\conda-bld\h5py_1490029446037\work\h5py\_objects.c:2867)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (C:\Minonda\conda-bld\h5py_1490029446037\work\h5py\_objects.c:2825)
  File "h5py\h5f.pyx", line 98, in h5py.h5f.create (C:\Minonda\conda-bld\h5py_1490029446037\work\h5py\h5f.c:2307)
OSError: Unable to create file (Unable to open file: name = 'd:\anton\desktop\main\экспертная система\экспертная система\алгоритмы прогнозирования\lstm 1\\weights.h5', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 302)

accuracy = 1,28600823045267
stdDev = 0,16164048197873
