



обучение алгоритма ANN 1...
СКРИПТ ОБУЧЕНИЯ ANN 1 ЗАПУЩЕН...

> время загрузки библиотек : 1.746 сек.

(5570, 4)

> время чтения данных  :  1.818 сек.

компиляция НС...

> время компиляции НС  : 2.589 сек.

обучение НС...

Train on 4448 samples, validate on 1112 samples

Epoch 1/1

0s - loss: 0.0474 - acc: 0.0216 - val_loss: 0.1431 - val_acc: 0.2149

сохранение модели: D:\Anton\Desktop\MAIN\Экспертная система\Экспертная система\Алгоритмы прогнозирования\ANN 1\\weights.h5



Using Theano backend.
Traceback (most recent call last):
  File "D:\Anton\Desktop\MAIN\Экспертная система\Экспертная система\Алгоритмы прогнозирования\ANN 1\train_script.py", line 109, in <module>
    model.save_weights(save_path)
  File "C:\Anaconda3\lib\site-packages\keras\models.py", line 738, in save_weights
    f = h5py.File(filepath, 'w')
  File "C:\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 107, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (C:\Minonda\conda-bld\h5py_1490029446037\work\h5py\_objects.c:2867)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (C:\Minonda\conda-bld\h5py_1490029446037\work\h5py\_objects.c:2825)
  File "h5py\h5f.pyx", line 98, in h5py.h5f.create (C:\Minonda\conda-bld\h5py_1490029446037\work\h5py\h5f.c:2307)
OSError: Unable to create file (Unable to open file: name = 'd:\anton\desktop\main\экспертная система\экспертная система\алгоритмы прогнозирования\ann 1\\weights.h5', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 302)

